### ISSUE TITLE
非Mac键盘不支持一键输入源切换功能

### ISSUE THREAD

**Issue by hacpai** [ghawkgu/isHUD#2]
外接了微软曲线2000键盘，微软自带的驱动可以自动设置为 ［Alt键］ 为 ［command 键］，［Win键］为［option键］。

用isHUD无法不支持［右option］切换。

**Comment by ghawkgu** [comment]
目前只支持Apple的键盘码，如需添加第三方键盘的支持，请参考https://github.com/ghawkgu/isHUD/blob/master/isHUD/ISHKeyCode.h
