### ISSUE TITLE
開機自動啟用

### ISSUE THREAD

**Issue by shuwn** [ghawkgu/isHUD#3]
isHUD 有開啟在登入時打開的 Funstion
當時現在常常重新開機時不會自動啟用
<img width="163" alt="Image_20220323_111707" src="https://user-images.githubusercontent.com/20023822/159617017-dfef2a73-cee2-4161-b163-c9e7b07f3fc8.png">
以下是我的系統版本
<img width="204" alt="image" src="https://user-images.githubusercontent.com/20023822/159617132-6856fd21-1588-4efc-af57-2f0153ee18b2.png">

**Comment by ghawkgu** [comment]
@shuwn 
謝謝反饋！很抱歉我還沒有M1的機器來確認這個問題，有條件我會做確認和測試，並針對M1進行升級。

另外我在把macOS升級到Monterey之後，也發生過不能自動啟動，或是切換輸入源的問題。
以下方法也許有效，可以試試看：
在系統偏好設定中找到login items，手工刪除isHUD，再點畫面中的 + 按鈕重新添加一次。
<img width="468" alt="image" src="https://user-images.githubusercontent.com/354068/159637849-a5309e0d-8431-481c-8f26-d1650144a676.png">

**Comment by shuwn** [comment]
> @shuwn 
> 
> 謝謝反饋！很抱歉我還沒有M1的機器來確認這個問題，有條件我會做確認和測試，並針對M1進行升級。
> 
> 
> 
> 另外我在把macOS升級到Monterey之後，也發生過不能自動啟動，或是切換輸入源的問題。
> 
> 以下方法也許有效，可以試試看：
> 
> 在系統偏好設定中找到login items，手工刪除isHUD，再點畫面中的 + 按鈕重新添加一次。
> 
> <img width="468" alt="image" src="https://user-images.githubusercontent.com/354068/159637849-a5309e0d-8431-481c-8f26-d1650144a676.png">
> 
> 

目前以此方法是可以暫時解決的
